#!/bin/ksh
#
# COMPONENT_NAME: perfpmr
#
# FUNCTIONS: none
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp.  2000
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# iostat.sh
#
# invoke iostat for specified interval and create interval and summary reports
#
export LANG=C
BIN=/usr/bin
SBIN=/usr/sbin


if [ $# -ne 1 ]; then
 echo "iostat.sh: usage: iostat.sh time"
 echo "      time is total time in seconds to be measured."
 exit 1
fi

# exit if iostat executable is not installed
if [ ! -f /usr/bin/iostat ]; then
  echo "     IOSTAT: /usr/bin/iostat command is not installed"
  echo "     IOSTAT:   This command is part of the 'bos.acct' fileset."
  exit 1
fi

# check total time specified for minimum amount of 60 seconds
if [ $1 -lt 60 ]; then
 echo Minimum time interval required is 60 seconds
 exit 1
fi

if [ -n "$PERFPMR_MONITOR_INTVLTIME" ]; then
        INTERVAL=$PERFPMR_MONITOR_INTVLTIME
else
	if [ $1 -lt 601 ]; then
 		INTERVAL=10
	else
 		INTERVAL=60
        fi

fi
let COUNT=$1/$INTERVAL


# need count+1 intervals for IOSTAT
let COUNT=COUNT+1
host=`$BIN/hostname -s`
dt=`$BIN/date`

echo "\n\n\n       I O S T A T    I N T E R V A L    O U T P U T   (iostat $INTERVAL $COUNT)\n" > iostat.int
echo "\n\n\n        I  O  S  T  A  T    S  U  M  M  A  R  Y    O  U  T  P  U  T\n\n\n" > iostat.sum
echo "\n\nHostname:    $host" >> iostat.int
echo "\n\nHostname:    $host" >> iostat.sum
echo "\n\nTime before run:   $dt" >> iostat.int
echo "\n\nTime before run:   $dt" >> iostat.sum
echo "Time before run:   $dt" >> iostat.total

trap 'kill -9 $!' 1 2 3 24
echo "\n     IOSTAT: Starting I/O Statistics Collector [IOSTAT]...."
let tottime=COUNT*INTERVAL
$BIN/iostat -R -a -T -D -l $tottime 1 >> iostat.total &
$BIN/iostat -m  > iostat.path
echo "\n\n----- lspath ------" >> iostat.path
$SBIN/lspath >> iostat.path
#$BIN/iostat -p 2>&1|$BIN/grep "No tapes found" >/dev/null && iostat_tape_exists=1
$BIN/iostat  -p -T  -D -l $INTERVAL $COUNT > iostat.p &
$BIN/iostat  -R -a -T -D -l $INTERVAL $COUNT > iostat.Dl &
#iostat $INTERVAL $COUNT > iostat.tmp &
$BIN/iostat -f $INTERVAL $COUNT > iostat.tmp &
$BIN/iostat -A -Q $INTERVAL $COUNT > aiostat.int &

# wait required interval
echo "     IOSTAT: Waiting for measurement period to end...."
wait

#####
#cp iostat.tmp iostat.matt

# save time after run
dt=`$BIN/date`
echo "\n\nTime after run :   $dt" >> iostat.int
echo "\n\nTime after run :   $dt">> iostat.sum
echo "\n\nTime after run :   $dt" >> iostat.total

echo "     IOSTAT: Generating reports...."

# put awk script in temp file for later use
$BIN/cat <<EOF > iostat.awk
BEGIN {
}

{
   if(\$1 == "tty:") { # next rec is tty data
      state = 1;
      ttyhdr = \$0; # save tty header
      ttycnt++;
      next;
   }

   if(\$1 == "Disks:") { # next rec is tty data
      state = 2;
      diskhdr = \$0; # save disk header
      diskcnt++;
      next;
   }

   if(state == 1) { # tty stuff
      stin    += \$1;
      stout   += \$2;
      suser   += \$3;
      ssys    += \$4;
      sidle   += \$5;
      siowait += \$6;
      state = 0;
      next;
   }

   if(state == 2) { # disk stuff
      if(NF > 0) { # while there are additional io entries
         disksum();
      }
      else {
         state = 0;
         nms = 0;
      }
      next;
   }
}

END {

   atin    = stin    / ttycnt;
   atout   = stout   / ttycnt;
   auser   = suser   / ttycnt;
   asys    = ssys    / ttycnt;
   aidle   = sidle   / ttycnt;
   aiowait = siowait / ttycnt;
   printf("\n");
   print ttyhdr;
   printf(" %12.1f %12.1f  %16.1f %8.1f  %9.1f %9.1f\n", \
      atin, atout, auser, asys, aidle, aiowait);

   print "\n" diskhdr;
   for(i = 1; i <= nms; i++) {
      name = nm[i];
      act = tmact[i]  / diskcnt;
      ps  = kbps[i]   / diskcnt;
      tp  = tps[i]    / diskcnt;
      rd  = kbread[i] / diskcnt;
      wr  = kbwrtn[i] / diskcnt;
      printf("%-13s  %5.1f  %8.1f  %8.1f  %16d %9d\n", \
         name, act, ps, tp, rd, wr);

   }
}

function disksum() {
   nms++;

   nm[nms]      = \$1;
   tmact[nms]  += \$2;
   kbps[nms]   += \$3;
   tps[nms]    += \$4;
   kbread[nms] += \$5;
   kbwrtn[nms] += \$6;
}
EOF

# get rid of first iostat report that shows stats since ipl
#B=$(/usr/bin/iostat 1 1 | /usr/bin/wc -l | /usr/bin/cut -c1-9)
#let B="$B+1"
#$BIN/tail +`echo $B` iostat.tmp > iostat.tmp2
#$BIN/mv iostat.tmp2 iostat.tmp

echo "\n\n\n" >> iostat.int
$BIN/cat iostat.tmp >> iostat.int

# generate summary report
echo "\n\n\n" >> iostat.sum
#$BIN/awk -f iostat.awk iostat.tmp >> iostat.sum

$BIN/rm  iostat.awk iostat.tmp

echo "     IOSTAT: Interval report is in file iostat.int"
echo "     IOSTAT: Summary report is in file iostat.sum"
